server:
  port: 8081


person:
     lastName: zhangsan
     age: 19
     boss: false
     borithday: 2017/12/11
     maps: {k1: v1,k2: 12}
     lists:
        - cat
        - dog
        - pig
     dog:
       name: xiaogou
       age: 1